### ISSUE TITLE
ActiveRecord is calling but I'm using Mongoid

### ISSUE THREAD

**Issue by iagopiimenta** [sevos/zeus-parallel_tests#29]
I'm using Mongoid but Zeus is calling ActiveRecord and shooting error.

```
4 processes for 1 specs, ~ 0 specs per process
~/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_specification.rb:167:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
from ~/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_specification.rb:163:in `connection_config'
from ~/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/zeus-parallel_tests-0.2.4/lib/zeus/parallel_tests/rails.rb:80:in `reconfigure_activerecord'
from ~/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/zeus-parallel_tests-0.2.4/lib/zeus/parallel_tests/rails.rb:66:in `spawn_slave'
from ~/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/zeus-parallel_tests-0.2.4/lib/zeus/parallel_tests/rails.rb:23:in `parallel_rspec_worker'
from ~/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/zeus-0.13.3/lib/zeus.rb:116:in `block in command'
....
from -e:1:in `<main>'

Took 6.995058758 seconds
```

Running `rake parallel:spec` instead of `zeus parallel_rspec spec` no error occurs.

I already removed the `database.yml`, set up the `application.rb` not require `rails/all`. No reference to ActiveRecord anywhere and still does not work.

`reconfigure_activerecord` is coming `defined?(ActiveRecord::Base)` but it was not defined in any config file of my application.

**Comment by schneidmaster** [comment]
I am (as of a few days ago) the new maintainer for this gem, and I'm looking through the old issues now. Are you still having this problem? If so, I will label it as a bug and add to my queue; if not, feel free to close the issue.

**Comment by White-Oak** [comment]
If using Mongo `zeus rake parallel:spec` runs just fine, but `zeus parallel_rspec spec` fails all tests.   
All fails are because there is no database (or it is empty) in the envinronment of the latter command.

I assume this is because RAILS_ENV is unset (too early?).
